### ISSUE TITLE
Left nav headings

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-components-gallery#5]
@AndrewArch said:

> I would like to see a 'Filters' heading on the left-hand column

I agree. Even if these are not (yet) expandible/collapsible, I think it would be good to give each filter group a heading, like in the tools list. This will make it look also a little more like the tools list.

**Comment by yatil** [comment]
There are headings for each filter group.

**Comment by nitedog** [comment]
IMO they could be visually a little stronger but we can close this for now and revisit in the redesign project.
