### ISSUE TITLE
spacing and design

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-components-gallery#9]
@dboudreau said:

> Provide a little more padding to the different elements, so it doesn't feel so compacted. Increase the difference in design between the tools descriptions and the metadata that comes with it (put the latter in a light graybox for example).

and @sharronrush said:

> I would like the UI to be even more closely aligned to that of the Tools list, but also understand the need for conservation of development resource time.

I agree. I think adding headings as proposed in issue #5 will also help with spacing and making it look more like the tools list. In addition, also add a space between the left nav and the main content. Currently it all looks like one big thing.

**Comment by yatil** [comment]
@dboudreau agreed that his comments were addressed by the changes I made. I asked @sharronrush for more information, but it as she abstained to further comment, I am inclined to close this issue.

**Comment by nitedog** [comment]
Happy to close it for now. We will need to revisit tool consistency in the redesign project anyway.
